server:
  port: 8686

spring:
  application:
    name: circuit-breaker-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

resilience4j:
  timelimiter:
    instances:
      notification-service:
        timeoutDuration: 30s
      user-service:
        timeoutDuration: 30s

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
