spring:
  application:
    name: eureka-server
  config:
    import: "optional:configserver:http://config-server:8888"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761