spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://circuit-breaker-service
          predicates:
            - Path=/users/**
        - id: notification-service
          uri: lb://circuit-breaker-service
          predicates:
            - Path=/notification/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8787
