spring:
  application:
    name: user-service
  kafka:
    bootstrap-servers: kafka:9092
  datasource:
    url: jdbc:postgresql://db:5432/userdb
    username: userapp
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
