spring:
  kafka:
    bootstrap-servers: kafka:9092

  application:
    name: user-service
  config:
    import: "optional:configserver:http://config-server:8888"
#    import: "optional:configserver:http://localhost:8888"
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/users_db
    username: userapp
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: localhost
